name: Khuton node CI/CD

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js 18.x # 노드 설치
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x # 버전 확인!

            - name: web docker build and push
              run: |
                docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                docker build -t ${{ secrets.DOCKER_REPO }}/khuthon-node .
                docker push ${{ secrets.DOCKER_REPO }}/khuthon-node     



