name: Khuton node CI/CD

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js 18.x # 노드 설치
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x # 버전 확인!

            - name: Login Dockerhub
              uses: docker/login-action@v1
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_PASSWORD}}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: ./
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/khuthon-node:latest



